name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  scoped_model: '^1.0.1'
  http: '^0.12.0+1'
  shared_preferences: '^0.5.1+2'
  rxdart: '^0.21.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  toast: ^0.1.4
  path_provider: ^0.5.0+1
  simple_permissions: ^0.1.9
  flutter_cupertino_date_picker: ^0.3.0
  local_notifications: ^0.0.7
  url_launcher: ^5.0.2

flutter:
  uses-material-design: true

  assets:
  - assets/kernel.png
  - assets/back_login.jpg

  fonts:
  - family: Oswald
    fonts:
    - asset: assets/Oswald-Bold.ttf
      weight: 700
